#!/usr/bin/env bash
set -e
# Ensure nbextensions are installed/enabled in Classic Notebook
jupyter nbextension install rise --py --sys-prefix
jupyter nbextension enable rise --py --sys-prefix
jupyter nbextension enable --py widgetsnbextension --sys-prefix
